"""0001 init

전체 스키마 부트스트랩 (모델-퍼스트 autogenerate + 수동 보강).
정본: docs/04-architecture/db-schema-opportunities.md (§3 DDL, §8 시드, §9 보강).

autogenerate가 생성한 테이블 DDL에 다음을 수동 보강:
  - pgcrypto 확장 (gen_random_uuid 등)
  - sources 시드(P0 4종 + narajangter_scsbid) · plans 시드
  - opportunity_status ENUM downgrade 시 DROP (왕복 안전)
  - 재임베딩/조회 부분 인덱스 + sweep_opportunity_status() 함수 (§9)

Revision ID: cf4a09a21225
Revises:
Create Date: 2026-06-18 22:34:22.232269
"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = 'cf4a09a21225'
down_revision = None
branch_labels = None
depends_on = None


# opportunities.status 가 참조하는 ENUM. 테이블 create_table 시 자동 생성되므로
# create_type=False 로 두고, upgrade 선두에서 명시 생성 / downgrade 말미에서 명시 DROP.
opportunity_status = postgresql.ENUM(
    "open", "closed", "unknown", name="opportunity_status", create_type=False
)

# P0 소스 시드 + 낙찰(narajangter_scsbid). opportunity_awards.source FK 대상.
_SOURCES_SEED = [
    {"code": "narajangter", "name": "나라장터(조달청) 입찰공고", "tier": 0,
     "collector": "narajangter", "enabled": True},
    {"code": "narajangter_scsbid", "name": "나라장터(조달청) 낙찰정보", "tier": 0,
     "collector": "narajangter_scsbid", "enabled": True},
    {"code": "bizinfo", "name": "기업마당(중기부)", "tier": 0,
     "collector": "bizinfo", "enabled": True},
    {"code": "kstartup", "name": "K-Startup(창업진흥원)", "tier": 0,
     "collector": "kstartup", "enabled": True},
    {"code": "ntis", "name": "NTIS 국가R&D통합공고", "tier": 0,
     "collector": "ntis", "enabled": True},
]

# 기본 플랜 시드 (billing.md, test 모드). amount=KRW.
_PLANS_SEED = [
    {"code": "basic_monthly", "name": "베이직(월간)", "amount": 99000,
     "interval": "month", "enabled": True},
]


def upgrade() -> None:
    # ── 확장 + ENUM (테이블보다 먼저) ──────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")   # pgvector (벡터 검색)
    opportunity_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('onboarding_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sources',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('collector', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('billing_keys',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('billing_key', sa.Text(), nullable=False),
    sa.Column('customer_key', sa.Text(), nullable=False),
    sa.Column('card_company', sa.String(length=32), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_contexts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),   # pgvector (EMBEDDING_DIM)
    sa.Column('content_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('embedded_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_settings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=20), server_default='alimtalk', nullable=False),
    sa.Column('send_hour', sa.SmallInteger(), nullable=False),
    sa.Column('send_empty', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('notifications',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=True),
    sa.Column('provider_msg_id', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'briefing_date', name='uq_notif_company_date')
    )
    op.create_table('opportunities',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_uid', sa.Text(), nullable=False),
    sa.Column('source_ord', sa.Integer(), nullable=True),
    sa.Column('detail_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('agency', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_raw', sa.Text(), nullable=True),
    sa.Column('budget_amount', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', opportunity_status, nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),   # pgvector (EMBEDDING_DIM)
    sa.Column('embedded_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_version', sa.String(length=64), nullable=True),
    sa.Column('dedup_group_id', sa.UUID(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['sources.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_uid', name='uq_opportunities_source_uid')
    )
    op.create_index(op.f('ix_opportunities_deadline'), 'opportunities', ['deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_dedup_group_id'), 'opportunities', ['dedup_group_id'], unique=False)
    op.create_index(op.f('ix_opportunities_posted_at'), 'opportunities', ['posted_at'], unique=False)
    op.create_index(op.f('ix_opportunities_source'), 'opportunities', ['source'], unique=False)
    op.create_table('opportunity_awards',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_uid', sa.Text(), nullable=False),
    sa.Column('bid_ntce_no', sa.Text(), nullable=True),
    sa.Column('bid_ntce_ord', sa.Integer(), nullable=True),
    sa.Column('bid_clsfc_no', sa.Text(), nullable=True),
    sa.Column('rbid_no', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('winner_name', sa.Text(), nullable=True),
    sa.Column('winner_bizno', sa.Text(), nullable=True),
    sa.Column('award_amount', sa.BigInteger(), nullable=True),
    sa.Column('award_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('demand_agency', sa.Text(), nullable=True),
    sa.Column('real_opening_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_award_date', sa.Date(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['sources.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_uid', name='uq_award_source_uid')
    )
    op.create_index('ix_award_bid_ntce_no', 'opportunity_awards', ['bid_ntce_no'], unique=False)
    op.create_table('source_ingestion_state',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('collected_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['sources.code'], ),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('matches',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('subscore', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'opportunity_id', name='uq_matches_company_opp')
    )
    op.create_table('opportunity_changes',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('old_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('new_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('old_ord', sa.Integer(), nullable=True),
    sa.Column('new_ord', sa.Integer(), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('billing_key_id', sa.UUID(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['billing_key_id'], ['billing_keys.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_code'], ['plans.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_sub_company')
    )
    op.create_table('user_opportunity_actions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_payment_key', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###

    # ── 수동 보강: 시드 ───────────────────────────────────────────
    sources_tbl = sa.table(
        "sources",
        sa.column("code", sa.String), sa.column("name", sa.String),
        sa.column("tier", sa.SmallInteger), sa.column("collector", sa.String),
        sa.column("enabled", sa.Boolean),
    )
    op.bulk_insert(sources_tbl, _SOURCES_SEED)

    plans_tbl = sa.table(
        "plans",
        sa.column("code", sa.String), sa.column("name", sa.String),
        sa.column("amount", sa.Integer), sa.column("interval", sa.String),
        sa.column("enabled", sa.Boolean),
    )
    op.bulk_insert(plans_tbl, _PLANS_SEED)

    # ── 수동 보강: 부분 인덱스 (db-schema §3·§9) ──────────────────
    op.create_index(
        "idx_opp_needs_embed", "opportunities", ["id"],
        postgresql_where=sa.text("embedded_hash IS DISTINCT FROM content_hash"),
    )
    op.create_index(
        "idx_opp_open_deadline", "opportunities", ["deadline"],
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_index(
        "idx_opp_source_posted", "opportunities",
        ["source", sa.text("posted_at DESC")],
    )
    op.create_index(
        "idx_cc_needs_embed", "company_contexts", ["id"],
        postgresql_where=sa.text("embedded_hash IS DISTINCT FROM content_hash"),
    )
    # pgvector 코사인 ANN 인덱스(opportunities 후보 검색 가속).
    op.create_index(
        "idx_opp_embedding_hnsw", "opportunities", ["embedding"],
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )

    # ── 수동 보강: 일일 status sweep 함수 (db-schema §9.2 C) ──────
    op.execute("""
        CREATE OR REPLACE FUNCTION sweep_opportunity_status() RETURNS void AS $$
            UPDATE opportunities SET status='closed'
             WHERE status='open' AND deadline IS NOT NULL AND deadline < now();
        $$ LANGUAGE sql;
    """)


def downgrade() -> None:
    # 수동 보강분 역순 정리 (테이블 DROP 전에)
    op.execute("DROP FUNCTION IF EXISTS sweep_opportunity_status()")
    op.drop_index("idx_opp_embedding_hnsw", table_name="opportunities")
    op.drop_index("idx_cc_needs_embed", table_name="company_contexts")
    op.drop_index("idx_opp_source_posted", table_name="opportunities")
    op.drop_index("idx_opp_open_deadline", table_name="opportunities")
    op.drop_index("idx_opp_needs_embed", table_name="opportunities")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('user_opportunity_actions')
    op.drop_table('subscriptions')
    op.drop_table('refresh_tokens')
    op.drop_table('opportunity_changes')
    op.drop_table('matches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('source_ingestion_state')
    op.drop_index('ix_award_bid_ntce_no', table_name='opportunity_awards')
    op.drop_table('opportunity_awards')
    op.drop_index(op.f('ix_opportunities_source'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_posted_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_dedup_group_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_deadline'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('notifications')
    op.drop_table('notification_settings')
    op.drop_table('company_contexts')
    op.drop_table('billing_keys')
    op.drop_table('sources')
    op.drop_table('plans')
    op.drop_table('companies')
    # ### end Alembic commands ###

    # ENUM 명시 DROP (왕복 안전: 재 upgrade 시 "type already exists" 방지)
    opportunity_status.drop(op.get_bind(), checkfirst=True)
